version: '3'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www/html
    depends_on:
      - db
    environment:
      DATABASE_HOST: db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 9080:8080

volumes:
  mysql-data:
